name: diod
description: Приложение для отображения расписания сотрудников отдела разработки.
version: 1.0.1+5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: any
  path_provider: any
  sentry: any
  dotenv: any
  http: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - lib/data/schemas/v1.sql
    - .app_env
